version: "2.2"
services:
  ocl-cache:
    #build: ./docker
    image: ghcr.io/cheminfo/ocl-cache-docker:head
    restart: always
    ulimits:
      core: 0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./db.sqlite:/node/db.sqlite
    ports:
      - 127.0.0.1:20822:20822
